// This file will be generated by Supabase CLI
// For now, we'll create a basic type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          postal_code: string | null
          tax_number: string | null
          description: string | null
          opening_hours: Json | null
          logo_url: string | null
          website_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
          archived_at: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          tax_number?: string | null
          description?: string | null
          opening_hours?: Json | null
          logo_url?: string | null
          website_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          tax_number?: string | null
          description?: string | null
          opening_hours?: Json | null
          logo_url?: string | null
          website_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
      }
      user_profiles: {
        Row: {
          id: string
          full_name: string | null
          phone: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          phone?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      memberships: {
        Row: {
          id: string
          user_id: string
          tenant_id: string
          role: 'owner' | 'admin' | 'staff'
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          tenant_id: string
          role?: 'owner' | 'admin' | 'staff'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          tenant_id?: string
          role?: 'owner' | 'admin' | 'staff'
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      modules: {
        Row: {
          id: string
          code: string
          name: string
          description: string | null
          icon: string | null
          default_enabled: boolean
          display_order: number
          created_at: string
          updated_at: string
        }
      }
      tenant_modules: {
        Row: {
          id: string
          tenant_id: string
          module_id: string
          is_enabled: boolean
          config_json: Json
          limits_json: Json
          created_at: string
          updated_at: string
        }
      }
      leads: {
        Row: {
          id: string
          tenant_id: string
          full_name: string
          email: string | null
          phone: string
          city: string | null
          message: string | null
          status: 'new' | 'in_progress' | 'waiting' | 'closed'
          source: string | null
          assigned_to: string | null
          converted_to_client_id: string | null
          gdpr_consent: boolean
          gdpr_consent_at: string | null
          created_at: string
          updated_at: string
          archived_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          full_name: string
          email?: string | null
          phone: string
          city?: string | null
          message?: string | null
          status?: 'new' | 'in_progress' | 'waiting' | 'closed'
          source?: string | null
          assigned_to?: string | null
          converted_to_client_id?: string | null
          gdpr_consent?: boolean
          gdpr_consent_at?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          full_name?: string
          email?: string | null
          phone?: string
          city?: string | null
          message?: string | null
          status?: 'new' | 'in_progress' | 'waiting' | 'closed'
          source?: string | null
          assigned_to?: string | null
          converted_to_client_id?: string | null
          gdpr_consent?: boolean
          gdpr_consent_at?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
      }
      clients: {
        Row: {
          id: string
          tenant_id: string
          full_name: string
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          postal_code: string | null
          tax_number: string | null
          notes: string | null
          created_from_lead_id: string | null
          created_at: string
          updated_at: string
          archived_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          full_name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          tax_number?: string | null
          notes?: string | null
          created_from_lead_id?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          full_name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          tax_number?: string | null
          notes?: string | null
          created_from_lead_id?: string | null
          created_at?: string
          updated_at?: string
          archived_at?: string | null
        }
      }
      notes: {
        Row: {
          id: string
          tenant_id: string
          entity_type: 'lead' | 'client'
          entity_id: string
          content: string
          created_by: string
          created_at: string
          updated_at: string
        }
      }
      tasks: {
        Row: {
          id: string
          tenant_id: string
          entity_type: 'lead' | 'client'
          entity_id: string
          title: string
          description: string | null
          due_date: string | null
          status: 'pending' | 'completed' | 'cancelled'
          assigned_to: string | null
          created_by: string
          created_at: string
          updated_at: string
          completed_at: string | null
        }
      }
      audit_log: {
        Row: {
          id: string
          tenant_id: string
          entity_type: string
          entity_id: string
          action: string
          before_data: Json | null
          after_data: Json | null
          actor_user_id: string | null
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
      }
    }
    Enums: {
      user_role: 'owner' | 'admin' | 'staff'
      lead_status: 'new' | 'in_progress' | 'waiting' | 'closed'
      note_entity_type: 'lead' | 'client'
      task_entity_type: 'lead' | 'client'
      task_status: 'pending' | 'completed' | 'cancelled'
    }
  }
}
